config/routes.rb
Rails.application.routes.draw do
  resources :apartments
  	root 'apartments#index' 
	get '/display', to: 'apartments#display'
end

app/models/apartment.rb
class Apartment < ApplicationRecord
	scope :price_range_3, -> {where("price > 1501 AND price <= 2000")}
	scope :price_range_4, -> {where("price > 2001")}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
	before_action :set_range, only: [:index]

	def index
		@apartments = Apartment.all.page(params[:page]).per(25)
  end

	def display
 		@display = Apartment.public_send(grouping_range).order(:price).page(params[:page]).per(25)
  end

  private

	def grouping_range
	 if %w(price_range_1 price_range_2 price_range_3 price_range_4).include? params[:choice]
       params[:choice]
     else
       :price_range_4
     end
	end

	def set_range
		#refactor
		@apartments_3 = Apartment.price_range_3.count
		@apartments_4 = Apartment.price_range_4.count

	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/apartments/display.html.erb
<div class="container">
  <h3>Apartments listings: sorted price ascending</h3>
  <%= link_to '< Homepage', apartments_path, class:'btn btn-primary btn-sm'%>
  <br>
  <%= paginate @display %>
  <table class="table table-striped">
    <tr>
      <th>Date</th>
      <th>Title</th>
      <th>Price</th>
    </tr>
   
    <% @display.each do |apartment| %>
      <tr>
        <td><%= apartment.date %></td>
        <td><%= apartment.title %></td>
        <td>$ <%= apartment.price%></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/apartments/index.html.erb
<div class="container text-center">
  <h2>Craigslist Scraper</h2>
  <h4>Apartment listings count by price range. Click to view. </h4>
 
    <ul>
        <%= link_to display_path("choice" => "price_range_1") do %>
        <ul class="btn btn-primary">Less than $1000: <%= pluralize(@apartments_1, "listing") %></ul>
        <% end %>

        <%= link_to display_path("choice" => "price_range_2") do %>
        <ul class="btn btn-primary">$1001 to $1500: <%= pluralize(@apartments_2, "listing") %></ul>
        <% end %>

        <%= link_to display_path("choice" => "price_range_3") do %>
        <ul class="btn btn-primary">$1501 to $2000: <%= pluralize(@apartments_3, "listing") %></ul>
        <% end %>  

        <%= link_to display_path("choice" => "price_range_4") do %>
        <ul class="btn btn-primary">Greater than $2000: <%= pluralize(@apartments_4, "listing") %></ul>
        <% end %>
  </ul>

</div>


<div class="container">
<h3>Apartments listings: latest to oldest </h3>
 <%= paginate @apartments %>
<table class="table table-striped">
  <tr>
    <th>Date</th>
    <th>Title</th>
    <th>Price</th>
  </tr>
 
  <% @apartments.each do |apartment| %>
    <tr>
      <td><%= apartment.date %></td>
      <td><%= apartment.title %></td>
      <td>$ <%= apartment.price%></td>
    </tr>
  <% end %>
</table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebScraper</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


  </head>

  <body>
    <%= yield %>
  </body>
</html>